stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/trading-bot
  IMAGE_TAG: $CI_COMMIT_REF_SLUG

# 1. Build the image using GitLab's Public Runners
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /#nobuild/'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'

# 2. Pull and Run on your VPS
deploy_to_vps:
  stage: deploy
  image: docker/compose:1.25.5
  tags:
    - annas-dev
  script:
    - echo "Logging into registry on VPS... "
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    
    - echo "Pulling latest image... $IMAGE_NAME:$IMAGE_TAG"
    - docker pull $IMAGE_NAME:$IMAGE_TAG
    
    - echo "Stopping existing container..."
    - docker stop active-trading-bot || true
    - docker rm active-trading-bot || true
    
    - echo "Starting new container..."
    - docker run -d --name active-trading-bot \
        -e TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" \
        -e TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID" \
        --restart unless-stopped \
        registry.gitlab.com/annasblackhat/trading-alert/trading-bot:dev
    
    - echo "Deployment successful!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
